name: Terraform Plan (PR)

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.tf'

jobs:
  plan-tf:
    runs-on: ubuntu-latest
    environment: prod
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      TF_VAR_S3_STATE_BUCKET_NAME: ${{ secrets.S3_STATE_BUCKET_NAME }}
      TF_VAR_JIRA_ENDPOINT: ${{ secrets.JIRA_ENDPOINT }}
      TF_VAR_JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
      TF_VAR_JIRA_API_KEY: ${{ secrets.JIRA_API_KEY }}
      TF_VAR_PROJECT_ID: ${{ secrets.PROJECT_ID }}
      TF_IN_AUTOMATION: "True"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
    
    - name: Terraform init
      id: init
      run: |
        cd filters
        terraform init -backend-config="bucket=${{ secrets.S3_STATE_BUCKET_NAME }}"
        
    - name: Run terraform plan
      id: plan
      run: |
        cd filters
        echo 'plan<<EOF' >> $GITHUB_OUTPUT
        terraform plan -no-color -out=tfplan >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT
        
    - name: Comment Plan
      id: comment-plan
      uses: peter-evans/create-or-update-comment@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          Terraform Plan:
          ```
          ${{ steps.plan.outputs.plan }}
          ```
          Merge this PR to apply these changes.
     
